# Generated by Django 5.2.9 on 2026-01-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumPhilosophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Our Curriculum Philosophy", max_length=200
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Curriculum Philosophy",
            },
        ),
        migrations.CreateModel(
            name="CurriculumPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("BookOpen", "Book Open"),
                            ("Palette", "Palette"),
                            ("Trophy", "Trophy"),
                            ("Globe", "Globe"),
                            ("Microscope", "Microscope"),
                            ("Calculator", "Calculator"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="e.g., Primary (Grades 1-5)", max_length=100
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        help_text="e.g., Foundation Building", max_length=100
                    ),
                ),
                ("description", models.TextField()),
                (
                    "subjects_offered",
                    models.TextField(
                        help_text="Enter subjects separated by commas, e.g., English, Mathematics, Science"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("BookOpen", "English / Literature"),
                            ("Calculator", "Mathematics"),
                            ("Microscope", "Sciences"),
                            ("Globe", "Social Studies"),
                            ("Languages", "Foreign Languages"),
                            ("Palette", "Arts & Crafts"),
                            ("Music", "Music & Performing Arts"),
                            ("Trophy", "Physical Education"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="corevalue",
            name="icon",
            field=models.CharField(
                choices=[
                    ("Award", "Excellence"),
                    ("Heart", "Integrity"),
                    ("Users", "Collaboration"),
                    ("Target", "Innovation"),
                ],
                max_length=20,
            ),
        ),
    ]
