# Generated by Django 5.2.9 on 2026-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_curriculumphilosophy_curriculumpillar_gradelevel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="facilities_images/")),
                (
                    "icon",
                    models.CharField(
                        help_text="Enter a lucide-react icon name (e.g., Library, Microscope)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
    ]
